{% set name = "cinemagoerng" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cinemagoer/cinemagoerng/archive/v{{ version }}.tar.gz
  sha256: 44e90d7c13e6bbcef81ed3ba1125228d8b7e5aede12e007d7b0ce967daa88018

build:
  entry_points:
    - cinemagoerng = cinemagoerng:cli.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - typedload
    - lxml
    - jmespath

test:
  imports:
    - cinemagoerng
  commands:
    - pip check
    - cinemagoerng --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Retrieve data from the IMDb.
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  dev_url: https://github.com/cinemagoer/cinemagoerng
  home: https://github.com/cinemagoer/cinemagoerng

extra:
  recipe-maintainers:
    - HeavyTony2
