{% set name = "cinemagoerng" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cinemagoer/cinemagoerng/archive/v{{ version }}.tar.gz
  sha256: f86084cfa14ac006f0c5d5ca0ec89be0f05776e824c9614af7a32c8e9402b176

build:
  entry_points:
    - cinemagoerng = cinemagoerng:cli.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - uv-build
  run:
    - python >={{ python_min }},<4.dev0
    - typedload >=2.38,<3.dev0
    - lxml >=5.4.0,<5.5.dev0
    - jmespath >=1.0.1,<1.1.dev0

test:
  imports:
    - cinemagoerng
  commands:
    - pip check
    - cinemagoerng --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Retrieve data from the IMDb.
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  dev_url: https://github.com/cinemagoer/cinemagoerng
  home: https://github.com/cinemagoer/cinemagoerng

extra:
  recipe-maintainers:
    - HeavyTony2
